# Generated by Django 3.1.6 on 2021-08-24 08:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='العنوان')),
                ('negative', models.BooleanField(verbose_name='سلبي')),
                ('newsscript', tinymce.models.HTMLField(blank=True, null=True, verbose_name='تفاصيل الخبر')),
                ('newsdate', models.DateField(verbose_name='تاريخ نشر الخبر')),
                ('newsurl', models.URLField(blank=True, default='--', max_length=1500, null=True, verbose_name='رابط الخبر')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='العنوان الذي يظهرفي الرابط')),
                ('newsvideo', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='رابط وسائط متعددة عن الخبر')),
                ('newsembedvideo', models.TextField(blank=True, null=True, verbose_name="تضمين وسائط متعددة عن الخبر مثل 'YOUTUBE'")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ادخال الخبر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الأخبار')),
                ('status', models.CharField(choices=[('d', 'قيد النشر و التعديل'), ('p', 'نشر'), ('w', 'سحب')], default='d', max_length=1, verbose_name='حالة الخبر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الاخبار',
                'db_table': 'news_news',
                'ordering': ['my_order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsName', models.CharField(max_length=200, verbose_name='نوع الخبر')),
            ],
            options={
                'verbose_name': 'نوع الخبر',
                'verbose_name_plural': 'انواع الاخبار',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(max_length=200, verbose_name='الجريدة')),
            ],
            options={
                'verbose_name': 'جريدة',
                'verbose_name_plural': 'الجرائد',
            },
        ),
        migrations.CreateModel(
            name='Newsimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('newsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News_image', to='news.news')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'db_table': 'news_newsimages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='', verbose_name='الملف')),
                ('newsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News_file', to='news.news')),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'الملفات',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='newstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newstype', verbose_name='نوع الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='papertype',
            field=models.ManyToManyField(blank=True, null=True, to='news.PaperType', verbose_name='الجريدة'),
        ),
    ]
