# Generated by Django 3.1.5 on 2021-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210216_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsvideo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
