# Generated by Django 3.1.5 on 2021-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210401_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsurl',
            field=models.URLField(blank=True, max_length=1500, null=True, verbose_name='رابط الخبر'),
        ),
    ]
