# Generated by Django 3.1.5 on 2021-04-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210418_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'news'},
        ),
    ]
