# Generated by Django 3.1.6 on 2021-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210428_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsembedvideo',
            field=models.TextField(blank=True, null=True, verbose_name="تضمين وسائط متعددة عن الخبر مثل 'YOUTUBE'"),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsvideo',
            field=models.URLField(blank=True, null=True, verbose_name='رفع ملف وسائط متعددة عن الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='العنوان الذي يظهرفي الرابط'),
        ),
    ]
