# Generated by Django 3.1.6 on 2021-04-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20210430_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsvideo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='رابط وسائط متعددة عن الخبر'),
        ),
    ]
