# Generated by Django 3.1.6 on 2021-05-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20210430_1222'),
        ('news', '0020_auto_20210428_1035'),
    ]

    operations = [
    ]
