# Generated by Django 3.1.6 on 2021-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_merge_20210504_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='papertype',
            field=models.ManyToManyField(blank=True, null=True, to='news.PaperType', verbose_name='الجريدة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='العنوان الذي يظهرفي الرابط'),
        ),
    ]
