# Generated by Django 3.1.6 on 2022-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20221003_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('WD', 'Withdraw')], default='DF', max_length=3, verbose_name='حالة الخبر'),
        ),
    ]
