# Generated by Django 3.1.6 on 2021-04-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FACILITY_DATA',
            fields=[
                ('FACILITY_DATA_ID', models.CharField(max_length=50, unique=True)),
                ('FACILITY_ID', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('NAME', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنشأه')),
                ('CEO_NAME', models.CharField(blank=True, max_length=200, null=True, verbose_name='المدير')),
                ('DETAILED_ADDRESS', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان')),
                ('PRIMARY_MOBILE', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموبايل')),
            ],
            options={
                'db_table': '"IDA"."FACILITY_DATA"',
                'ordering': ['FACILITY_ID'],
            },
        ),
        migrations.CreateModel(
            name='INDUSTRIAL_PRODUCTS',
            fields=[
                ('PRODUCT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PRODUCT_TITLE', models.CharField(blank=True, max_length=1000, null=True, verbose_name='اسم المنتج')),
            ],
            options={
                'db_table': '"IDA"."INDUSTRIAL_PRODUCTS"',
                'ordering': ['PRODUCT_TITLE'],
            },
        ),
        migrations.CreateModel(
            name='MEASURING_UNITS',
            fields=[
                ('UNIT_ID', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('UNIT_TITLE_AR', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"IDA"."MEASURING_UNITS"',
            },
        ),
        migrations.CreateModel(
            name='INDUSTRIAL_REGISTRY',
            fields=[
                ('REGISTRY_ID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('REGISTRY_NUMBER', models.CharField(max_length=100)),
                ('FACILITY_DATA', models.ForeignKey(db_column='FACILITY_DATA_ID', on_delete=django.db.models.deletion.CASCADE, related_name='my', to='filter.facility_data', to_field='FACILITY_DATA_ID')),
            ],
            options={
                'db_table': '"IDA"."INDUSTRIAL_REGISTRY"',
            },
        ),
        migrations.CreateModel(
            name='FACILITY_PRODUCTS',
            fields=[
                ('FAC_PROD_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PRODUCT_QUANTITY', models.DecimalField(decimal_places=3, max_digits=38)),
                ('FACILITY_ID', models.ForeignKey(db_column='FACILITY_ID', on_delete=django.db.models.deletion.CASCADE, to='filter.facility_data')),
                ('PRODUCT_ID', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, to='filter.industrial_products')),
                ('UNIT_ID', models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='ty', to='filter.measuring_units')),
            ],
            options={
                'db_table': '"IDA"."FACILITY_PRODUCTS"',
            },
        ),
        migrations.AddField(
            model_name='facility_data',
            name='Prouducts',
            field=models.ManyToManyField(related_name='ty', through='filter.FACILITY_PRODUCTS', to='filter.INDUSTRIAL_PRODUCTS', verbose_name='المنتجات'),
        ),
    ]
